baseURL = "https://csehuman.github.io/"
title = "csehumanì˜ ë¡œê·¸"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[params.label]
icon = "/images/whale.png"  # Remove 'static' from path
iconHeight = 35

[params.assets]
favicon = "/images/whale.png"
apple_touch_icon = "/images/whale.png"
safari_pinned_tab = "/images/whale.png"

[params.homeInfoParams]
Title = "ì•ˆë…•í•˜ì„¸ìš” ğŸ‘‹"
Content = "ì´ì¢…ì¸ì…ë‹ˆë‹¤ğŸ˜"

[taxonomies]
category = "categories"
tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true